### PR TITLE
Cli options

### PR DESCRIPTION
**Pull request by joao-bapdm**
Just a function for loading a json file with the model parameters and some CLI options, trivial to expand.

for instance, you can have a parameter file called `model.json` with the following content:
```
{
    "opts": {
        "method": "CG",
        "variant": "spectral",
        "degree": 1,
        "dimension": 2,
        "cmin": 1,
        "cmax": 3.5,
        "rmin": 1,
        "timestepping": "explicit"
    },
    "mesh": {
        "nz": 60,
        "nx": 60,
        "Lz": 2.0,
        "Lx": 2.0,
        "Ly": 0.0,
        "meshfile": null,
        "truemodel": null
    },
    "PML": {
        "status": false,
        "outer_bc": "reflective",
        "damping_type": "polynomial",
        "exponent": 1,
        "cmax": 4.7,
        "R": 0.001,
        "lz": 0.5,
        "lx": 0.5,
        "ly": 0.0
    },
    "acquisition": {
        "source_type": "Ricker",
        "amplitude": 10.0,
        "num_sources": 1,
        "src_XMIN": 0.999,
        "src_XMAX": 1.001,
        "rec_XMIN": 0.05,
        "rec_XMAX": 1.95,
        "src_depth": [
            1.95
        ],
        "frequency": 2,
        "delay": 1.0,
        "num_receivers": 21,
        "rec_depth": [
            1.95
        ]
    },
    "water": {
        "depth": 1.85,
        "velocity": 1.51
    },
    "timeaxis": {
        "t0": 0.0,
        "tf": 2.6,
        "dt": 0.001,
        "nspool": 5,
        "fspool": 1
    },
    "material": {
        "type": "simp",
        "vp_min": 1,
        "vp_max": 3.5,
        "penal": 1
    },
    "parallelism": {
        "type": "off"
    },
    "cplex": {
        "beta": 0.01,
        "mul_beta": 25,
        "use_rmin": true,
        "mul_rmin": 30,
        "lim_rmin": 50,
        "gamma_m": 0.9,
        "gamma_v": 0.9
    },
    "inversion": {
        "freq_bands": [
            null
        ],
        "optimizer": "cplex"
    },
    "data": {
        "shots": "shots/ls_simple",
        "record": "record",
        "initfile": null,
        "resultfile": "vp_ls_simple_3_d_cplex.hdf5"
    },
    "output": {
        "outdir": "output_fig3_d"
    }
}
```

pass it through the command line with the `-c` or `--config-file` option, and optionally overwrite default options. For instance, running `python load_parameters.py -c model.json -i input.msh -o output.hdf5` will overwrite input and output files. Other options can be easily added. 

`load_parameters.py`:

```
import os
import sys
import spyro

model = spyro.io.load_model()

print(model["data"])
```

### CODE REVIEW

**Comment by krober10nd** [comment]
so the `load_parameters.py` will overwrite the default input file options which I presume are set in `load_parameters.py`?

**Comment by joao-bapdm** [comment]
load_parameters is that 7 lines script calling spyro.io.load_model(). That function imports the json file passed with the -c option, in this case, `model.json`. 

The -i and -o are options are mainly to show that one can overwrite what was read from the json file by cli as well.

That's just something I found useful for scripting many tests, but maybe it needs some working before being useful for Spyro in general

**Comment by krober10nd** [comment]
> but maybe it needs some working before being useful for Spyro in general

yes I agree.

**Comment by krober10nd** [comment]
Hello senhor João, I'm going to close this for now. If you want to improve it later on we can rebase with master.

**Pull request closed without merging**
